FROM sonarsource/sonar-scanner-cli:latest

USER root

RUN yum install -y bash
RUN yum install -y jq gettext

ADD BP-BASE-SHELL-STEPS /opt/buildpiper/shell-functions/
# ADD BP-BASE-SHELL-STEPS/data /opt/buildpiper/data

ENV APPLICATION_NAME=""
ENV ORGANIZATION=""
ENV SOURCE_KEY=""
ENV REPORT_FILE_PATH=""
ENV JAVA_BINARIES=""

ENV SONAR_TOKEN=""
ENV SONAR_URL=""
ENV SONAR_ARGS=""
ENV MI_SERVER_ADDRESS=""
ENV ACTIVITY_SUB_TASK_CODE=SONARQUBE-SCANNER
ENV SLEEP_DURATION=5s
ENV VALIDATION_FAILURE_ACTION=WARNING
ENV NODE_OPTIONS --max-old-space-size=8192

COPY build.sh .
ENTRYPOINT [ "./build.sh" ]
